### ISSUE TITLE
Different Python Paths for Local and Github Actions

### ISSUE THREAD

**Issue by r0f1** [RobertCraigie/pyright-python#203]
Hi everybody,

My `.pre-commit-config.yaml` looks like this:
```yaml
- repo: https://github.com/RobertCraigie/pyright-python
  rev: v1.1.322
  hooks:
  - id: pyright
    args: ["--pythonpath", ".venv/Scripts/python.exe"]
```
and this all works fine as long as I execute it locally. As soon as I push it to Github, and Github Actions kicks in,, it does no longer work because pyright cannot find any of the installed packages (=for every single import statement there is a `reportMissingImports` error thrown). So I thought I change the config file to this:
```yaml
- repo: https://github.com/RobertCraigie/pyright-python
  rev: v1.1.322
  hooks:
  - id: pyright
     args: ["--pythonpath", ".venv/bin/python"]
```
This would work on Github, but does no longer work locally.
I was looking through the [documentation](https://github.com/microsoft/pyright/blob/main/docs/configuration.md) and could not find a mention of the `--pythonpath` argument. 

How can I specify the pythonpath such that pyright works both locally and on Github?

**Comment by jobh** [comment]
I don't know if this helps, or if it's anywhere close to correct, but I was struggling with a similar issue (wanting different `pythonpath`s) and ended up with this beauty:

```
- repo: https://github.com/RobertCraigie/pyright-python
  rev: v1.1.325
  hooks:
  - id: pyright
    types_or: [python, pyi]
    require_serial: true
    entry: bash -c 'pyright --pythonpath $(python -c "import os,sys; print(os.path.realpath(sys.executable))") "$@"' -
```
