### ISSUE TITLE
Add a less verbose second hook

### ISSUE THREAD

**Issue by randolf-scholz** [RobertCraigie/pyright-python#269]
`pyright`'s output is quite verbose for a pre-commit hook. We can combine it with grep to give much less verbose output:

```yaml
hooks:
  - id: pyright
    entry: bash -c '! pyright "$@" | grep -Po "(?<=$PWD/)(.*:.*)"' --
```

Does it make sense to add this as a second hook, maybe "pyright-minimal"?

Of course, a caveat here is that it is less robust and could silently fail if `$PWD` contains funny special characters.
